# Generated by Django 4.1.3 on 2022-11-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manga",
            name="author",
            field=models.TextField(default="none", max_length=254),
            preserve_default=False,
        ),
    ]
