# Generated by Django 4.1.3 on 2022-12-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0002_manga_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="manga",
            name="cover",
            field=models.ImageField(default="media/loading.jpg", upload_to="cover"),
        ),
    ]
