# Generated by Django 4.1.3 on 2022-12-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0003_manga_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manga",
            name="cover",
            field=models.ImageField(default="loading.jpg", upload_to="cover"),
        ),
    ]
