# Generated by Django 4.1.3 on 2022-12-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0007_alter_manga_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("images", models.FileField(upload_to="")),
            ],
        ),
    ]
