# Generated by Django 4.1.3 on 2023-01-01 14:11

from django.db import migrations, models
import django.db.models.deletion
import mangas.models


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0013_alter_chapter_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="manga",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mangas.manga",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="images",
            field=models.ImageField(upload_to=mangas.models.path_file_name),
        ),
    ]
