# Generated by Django 4.1.3 on 2023-01-01 14:16

from django.db import migrations, models
import django.db.models.deletion
import mangas.models


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0014_chapter_manga_alter_chapter_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="C",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("images", models.ImageField(upload_to=mangas.models.path_file_name)),
                (
                    "manga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mangas.manga",
                    ),
                ),
            ],
        ),
    ]
