# Generated by Django 4.1.3 on 2023-01-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0015_c"),
    ]

    operations = [
        migrations.DeleteModel(
            name="C",
        ),
    ]
