# Generated by Django 4.1.3 on 2023-01-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0016_delete_c"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
