# Generated by Django 4.1.3 on 2023-01-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0017_alter_chapter_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manga",
            name="num_of_chapters",
            field=models.IntegerField(default=0),
        ),
    ]
