# Generated by Django 4.1.3 on 2023-01-11 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0021_alter_chapter_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manga",
            name="content",
            field=models.TextField(max_length=1000),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("timestamp", models.DateField(auto_now_add=True)),
                (
                    "manga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mangas.manga"
                    ),
                ),
            ],
        ),
    ]
