# Generated by Django 4.1.3 on 2023-02-03 02:25

from django.db import migrations, models
import django.db.models.deletion
import mangas.models


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0022_alter_manga_content_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Volume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("images", models.FileField(upload_to=mangas.models.path_file_name)),
                (
                    "manga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mangas.manga",
                    ),
                ),
            ],
        ),
    ]
