# Generated by Django 4.1.3 on 2023-02-03 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0023_volume"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manga",
            old_name="num_of_chapters",
            new_name="num_of_volumes",
        ),
    ]
