# Generated by Django 4.1.3 on 2023-02-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0024_rename_num_of_chapters_manga_num_of_volumes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volume",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
