# Generated by Django 4.1.3 on 2023-02-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0025_alter_volume_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volume",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
