# Generated by Django 4.1.3 on 2023-02-09 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0027_alter_volume_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="volume",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
