# Generated by Django 4.1.3 on 2023-02-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0028_volume_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volume",
            name="timestamp",
            field=models.DateField(auto_now_add=True),
        ),
    ]
