# Generated by Django 4.1.3 on 2023-02-20 16:24

from django.db import migrations, models
import mangas.models


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0030_chapter_volume"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volume",
            name="images",
        ),
        migrations.AddField(
            model_name="volume",
            name="num_of_chapters",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="images",
            field=models.FileField(upload_to=mangas.models.path_chapter_name),
        ),
    ]
